/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 16-May-2024 07:14:34
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 40
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-c ode  */
#include "stdint.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020a\extern\include\tmwtypes.h 
 */
const int BL = 40;
const double B[40] = {
  -0.009989618909284, -0.02029074095165,-0.003658761822981,  0.01191660252522,
  -0.006240071821678,-0.007667007974536,  0.01485339446217,-0.004012265112455,
   -0.01571093256692,  0.02001544874986, 0.002248284375145, -0.02939791710243,
    0.02520172811786,  0.01689416127921, -0.05353521126487,  0.02916133042266,
    0.05668551319652,  -0.1206160212491,  0.03134960555358,   0.5345021687799,
     0.5345021687799,  0.03134960555358,  -0.1206160212491,  0.05668551319652,
    0.02916133042266, -0.05353521126487,  0.01689416127921,  0.02520172811786,
   -0.02939791710243, 0.002248284375145,  0.02001544874986, -0.01571093256692,
  -0.004012265112455,  0.01485339446217,-0.007667007974536,-0.006240071821678,
    0.01191660252522,-0.003658761822981, -0.02029074095165,-0.009989618909284
};
